name: Build dylib file

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: clone theos repo
        run: git clone --recursive https://github.com/theos/theos.git
      - name: install sdks
        run: curl -fsSL https://github.com/theos/sdks/tarball/master | tar -xz --strip-components=1