name: Build dylib file

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install include tools
        run: |
          brew install ldid xz perl
          hash -r
          PERL_MM_USE_DEFAULT=1 cpan IO::Compress::Lzma
      - name: clone theos repo
        run: git clone --recursive https://github.com/theos/theos.git
      - name: install sdks
        run: |
          cd ./theos/sdks
          curl -fsSL https://github.com/theos/sdks/tarball/master | tar -xz --strip-components=1
          exec bash
      - name: build
        run: make